"""create transaction sync states

Revision ID: 55489047a1ab
Revises: b68eea2e0615
Create Date: 2026-09-01 18:50:27.364605

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55489047a1ab"
down_revision: str | Sequence[str] | None = "b68eea2e0615"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_sync_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider_name", sa.String(), nullable=False),
        sa.Column("provider_connection_id", sa.String(), nullable=False),
        sa.Column("cursor", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(provider_connection_id)) > 0",
            name=op.f("ck_transaction_sync_states_provider_connection_id_nonempty"),
        ),
        sa.CheckConstraint(
            "length(trim(provider_name)) > 0",
            name=op.f("ck_transaction_sync_states_provider_name_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transaction_sync_states_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_sync_states")),
        sa.UniqueConstraint(
            "provider_name",
            "provider_connection_id",
            name="uq_transaction_sync_states_provider_connection",
        ),
    )
    op.create_index(
        op.f("ix_transaction_sync_states_user_id"),
        "transaction_sync_states",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transaction_sync_states_user_id"), table_name="transaction_sync_states"
    )
    op.drop_table("transaction_sync_states")
    # ### end Alembic commands ###
