"""create external transactions

Revision ID: c7bf99d9a6e7
Revises: 94672dd029a3
Create Date: 2026-08-23 15:58:57.814164

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7bf99d9a6e7"
down_revision: str | Sequence[str] | None = "94672dd029a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_financial_accounts_ownership", "financial_accounts", ["id", "user_id"]
    )
    op.create_table(
        "external_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("financial_account_id", sa.Uuid(), nullable=False),
        sa.Column("provider_transaction_id", sa.String(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'removed')",
            name=op.f("ck_external_transactions_status"),
        ),
        sa.CheckConstraint(
            "length(trim(provider_transaction_id)) > 0",
            name=op.f("ck_external_transactions_provider_id_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_account_id", "user_id"],
            ["financial_accounts.id", "financial_accounts.user_id"],
            name=op.f(
                "fk_external_transactions_financial_account_id_financial_accounts"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_transactions")),
        sa.UniqueConstraint(
            "user_id",
            "provider_transaction_id",
            name="uq_external_transactions_provider_identity",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("external_transactions")
    op.drop_constraint(
        "uq_financial_accounts_ownership", "financial_accounts", type_="unique"
    )
    # ### end Alembic commands ###
