"""create journals and postings

Revision ID: f8ef7beaa235
Revises: c7bf99d9a6e7
Create Date: 2026-08-23 16:20:34.309921

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8ef7beaa235"
down_revision: str | Sequence[str] | None = "c7bf99d9a6e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("external_transaction_id", sa.Uuid(), nullable=False),
        sa.Column("reversal_of_entry_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "reversal_of_entry_id IS NULL OR reversal_of_entry_id <> id",
            name=op.f("ck_journal_entries_not_self_reversal"),
        ),
        sa.ForeignKeyConstraint(
            ["external_transaction_id"],
            ["external_transactions.id"],
            name=op.f(
                "fk_journal_entries_external_transaction_id_external_transactions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_entry_id", "external_transaction_id"],
            ["journal_entries.id", "journal_entries.external_transaction_id"],
            name=op.f("fk_journal_entries_reversal_of_entry_id_journal_entries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
        sa.UniqueConstraint(
            "id", "external_transaction_id", name="uq_journal_entries_identity"
        ),
        sa.UniqueConstraint("reversal_of_entry_id", name="uq_journal_entries_reversal"),
    )
    op.create_table(
        "postings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.SmallInteger(), nullable=False),
        sa.Column("ledger_account", sa.String(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "length(trim(ledger_account)) > 0",
            name=op.f("ck_postings_ledger_account_nonempty"),
        ),
        sa.CheckConstraint(
            "line_number >= 0", name=op.f("ck_postings_line_number_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_postings_journal_entry_id_journal_entries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_postings")),
        sa.UniqueConstraint(
            "journal_entry_id", "line_number", name="uq_postings_journal_line"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("postings")
    op.drop_table("journal_entries")
    # ### end Alembic commands ###
